name: IIS Deployment of Riyadbank Application

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Riyadbank Website
    runs-on: ubuntu-18.04
    steps:
      - name: Download the Source Code
        uses: actions/checkout@v3
      
      - name: Setup the Dotnet 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6'

      - name: Verify the Dotnet Version
        run: dotnet --version

      - name: Build the Application
        run: dotnet build --configuration Release

      - name: Publish the package as public folder
        run: dotnet publish -c Release -o public

      - name: Zip the Public folder as public.zip
        run: zip -r public.zip public/
      
      - name: Check the Public Zip File
        run: ls -l public.zip

      - name: Copy the Public Folder to Ubuntu
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'public/*'
          remote: 'public/'
          host: ${{secrets.HOST}}
          user: ${{secrets.USER}}
          password: ${{secrets.PASSWORD}}
          ssh_options: -o StrictHostKeyChecking=no
          pre_upload: rmdir /s /q public
          post_upload: iisreset /stop && xcopy /s /y public C:\inetpub\wwwroot\ && iisreset /start